<center><h1>Controle de ISO</h1></center>
<div class='bordasimples'>
<table width='100%' class='menu' cellpadding='0' cellspacing='0' bgcolor='#F0F0F0'>
	<tr><td>
		<ul>
		<?php		
			menuli("Inclus&atilde;o","cadastrar");
			menuli("Consulta","listar");
			menuli("Andamento","andamento");
			menuli("Prazos","prazo");
		?>
		</ul>	
	</td></tr>
	<tr><td>
<?
	
	//if ($opcao=="cadastrar") echo "<center><h1>Novo MATERIAL</h1></center>";
	//if ($opcao=="atualizar") echo "<center><h1>Editar MATERIAL</h1></center>";
	//if ($opcao=="listar") echo "<center><h1>Materiais cadastrados</h1></center>";
	//if ($opcao=="buscar") echo "<center><h1>Procurar MATERIAL</h1></center>";
	//if ($opcao=="excluir") echo "<center><h1>Exclus&atilde;o de MATERIAL</h1></center>";

?>
	</td></tr>
</table>
</div>
<br>
