<center><h1 class='noprint'>Inativo PMPR</h1></center>

<table width='100%' class='menu' cellpadding='0' cellspacing='0' bgcolor='#F0F0F0'>
	<tr><td>
		<ul>
		<?php		
			menuli("Consulta","listar");
		?>
		</ul>	
	</td></tr>
	<tr><td>
<?
	
	//if ($opcao=="cadastrar") echo "<center><h1>Novo MATERIAL</h1></center>";
	//if ($opcao=="atualizar") echo "<center><h1>Editar MATERIAL</h1></center>";
	//if ($opcao=="listar") echo "<center><h1>Materiais cadastrados</h1></center>";
	//if ($opcao=="buscar") echo "<center><h1>Procurar MATERIAL</h1></center>";
	//if ($opcao=="excluir") echo "<center><h1>Exclus&atilde;o de MATERIAL</h1></center>";

?>
	</td></tr>
</table>

