<template>
    <div>
        <select name="id_municipio" :value="id_municipio" class="form-control" @click="$emit('input', $event.target.value)">
            <option value="">Selecione</option>
            <option value="80024">ABATIA</option>
            <option value="80060">ADRIANOPOLIS</option>
            <option value="80132">AGUDOS DO SUL</option>
            <option value="80168">ALMIRANTE TAMANDARE</option>
            <option value="80180">ALTAMIRA DO PARANA</option>
            <option value="89612">ALTO PARAISO</option>
            <option value="80264">ALTO PARANA</option>
            <option value="80276">ALTO PIQUIRI</option>
            <option value="80240">ALTONIA</option>
            <option value="80324">ALVORADA DO SUL</option>
            <option value="80336">AMAPORA</option>
            <option value="80372">AMPERE</option>
            <option value="80378">ANAHY</option>
            <option value="80384">ANDIRA</option>
            <option value="80408">ANGULO</option>
            <option value="80432">ANTONINA</option>
            <option value="80444">ANTONIO OLINTO</option>
            <option value="80492">APUCARANA</option>
            <option value="80516">ARAPONGAS</option>
            <option value="80528">ARAPOTI</option>
            <option value="80540">ARAPUA</option>
            <option value="80576">ARARUNA</option>
            <option value="80588">ARAUCARIA</option>
            <option value="80612">ARIRANHA DO IVAI</option>
            <option value="80624">ASSAI</option>
            <option value="80636">ASSIS CHATEAUBRIAND</option>
            <option value="80648">ASTORGA</option>
            <option value="80660">ATALAIA</option>
            <option value="80744">BALSA NOVA</option>
            <option value="80756">BANDEIRANTES</option>
            <option value="80780">BARBOSA FERRAZ</option>
            <option value="80828">BARRA DO JACARE</option>
            <option value="80804">BARRACAO</option>
            <option value="80924">BELA VISTA DA CAROBA</option>
            <option value="80960">BELA VISTA DO PARAISO</option>
            <option value="81020">BITURUNA</option>
            <option value="81032">BOA ESPERANCA</option>
            <option value="81056">BOA ESPERANCA DO IGUACU</option>
            <option value="81068">BOA VENTURA DE SAO ROQUE</option>
            <option value="81104">BOA VISTA DA APARECIDA</option>
            <option value="81116">BOCAIUVA DO SUL</option>
            <option value="81140">BOM JESUS DO SUL</option>
            <option value="81176">BOM SUCESSO</option>
            <option value="81188">BOM SUCESSO DO SUL</option>
            <option value="81236">BORRAZOPOLIS</option>
            <option value="81245">BRAGANEY</option>
            <option value="81260">BRASILANDIA DO SUL</option>
            <option value="81308">CAFEARA</option>
            <option value="81332">CAFELANDIA</option>
            <option value="81344">CAFEZAL DO SUL</option>
            <option value="81380">CALIFORNIA</option>
            <option value="81404">CAMBARA</option>
            <option value="81416">CAMBE</option>
            <option value="81428">CAMBIRA</option>
            <option value="81464">CAMPINA DA LAGOA</option>
            <option value="81488">CAMPINA DO SIMAO</option>
            <option value="81476">CAMPINA GRANDE DO SUL</option>
            <option value="81500">CAMPO BONITO</option>
            <option value="81536">CAMPO DO TENENTE</option>
            <option value="81548">CAMPO LARGO</option>
            <option value="81572">CAMPO MAGRO</option>
            <option value="81584">CAMPO MOURAO</option>
            <option value="81608">CANDIDO DE ABREU</option>
            <option value="82226">CANDOI</option>
            <option value="81656">CANTAGALO</option>
            <option value="81680">CAPANEMA</option>
            <option value="81692">CAPITAO LEONIDAS MARQUES</option>
            <option value="81704">CARAMBEI</option>
            <option value="81740">CARLOPOLIS</option>
            <option value="81776">CASCAVEL</option>
            <option value="81800">CASTRO</option>
            <option value="81812">CATANDUVAS</option>
            <option value="81872">CENTENARIO DO SUL</option>
            <option value="81896">CERRO AZUL</option>
            <option value="81908">CEU AZUL</option>
            <option value="81920">CHOPINZINHO</option>
            <option value="81932">CIANORTE</option>
            <option value="81944">CIDADE GAUCHA</option>
            <option value="81968">CLEVELANDIA</option>
            <option value="81980">COLOMBO</option>
            <option value="82040">COLORADO</option>
            <option value="82088">CONGONHINHAS</option>
            <option value="82100">CONSELHEIRO MAIRINCK</option>
            <option value="82124">CONTENDA</option>
            <option value="82148">CORBELIA</option>
            <option value="82160">CORNELIO PROCOPIO</option>
            <option value="82172">CORONEL DOMINGOS SOARES</option>
            <option value="82196">CORONEL VIVIDA</option>
            <option value="82220">CORUMBATAI DO SUL</option>
            <option value="82328">CRUZ MACHADO</option>
            <option value="82280">CRUZEIRO DO IGUACU</option>
            <option value="82292">CRUZEIRO DO OESTE</option>
            <option value="82316">CRUZEIRO DO SUL</option>
            <option value="82340">CRUZMALTINA</option>
            <option value="82362">CURITIBA</option>
            <option value="82580">CURIUVA</option>
            <option value="82628">DIAMANTE DO NORTE</option>
            <option value="82620">DIAMANTE DO OESTE</option>
            <option value="82616">DIAMANTE DO SUL</option>
            <option value="82664">DOIS VIZINHOS</option>
            <option value="82688">DOURADINA</option>
            <option value="82712">DOUTOR CAMARGO</option>
            <option value="89504">DOUTOR ULYSSES</option>
            <option value="82796">ENEAS MARQUES</option>
            <option value="82820">ENGENHEIRO BELTRAO</option>
            <option value="82826">ENTRE RIOS DO OESTE</option>
            <option value="81044">ESPERANCA NOVA</option>
            <option value="82892">ESPIGAO ALTO DO IGUACU</option>
            <option value="82952">FAROL</option>
            <option value="82964">FAXINAL</option>
            <option value="83006">FAZENDA RIO GRANDE</option>
            <option value="83012">FENIX</option>
            <option value="83024">FERNANDES PINHEIRO</option>
            <option value="83060">FIGUEIRA</option>
            <option value="83096">FLOR DA SERRA DO SUL</option>
            <option value="83108">FLORAI</option>
            <option value="83120">FLORESTA</option>
            <option value="83132">FLORESTOPOLIS</option>
            <option value="83156">FLORIDA</option>
            <option value="83204">FORMOSA DO OESTE</option>
            <option value="83216">FOZ DO IGUACU</option>
            <option value="88775">FOZ DO JORDAO</option>
            <option value="83228">FRANCISCO ALVES</option>
            <option value="83240">FRANCISCO BELTRAO</option>
            <option value="83312">GENERAL CARNEIRO</option>
            <option value="83330">GODOY MOREIRA</option>
            <option value="83336">GOIOERE</option>
            <option value="83348">GOIOXIM</option>
            <option value="83384">GRANDES RIOS</option>
            <option value="83408">GUAIRA</option>
            <option value="83432">GUAIRACA</option>
            <option value="83456">GUAMIRANGA</option>
            <option value="83480">GUAPIRAMA</option>
            <option value="83504">GUAPOREMA</option>
            <option value="83528">GUARACI</option>
            <option value="83564">GUARANIACU</option>
            <option value="83576">GUARAPUAVA</option>
            <option value="83588">GUARAQUECABA</option>
            <option value="83600">GUARATUBA</option>
            <option value="83672">HONORIO SERPA</option>
            <option value="83696">IBAITI</option>
            <option value="83708">IBEMA</option>
            <option value="83732">IBIPORA</option>
            <option value="83756">ICARAIMA</option>
            <option value="83780">IGUARACU</option>
            <option value="83798">IGUATU</option>
            <option value="83816">IMBAU</option>
            <option value="83840">IMBITUVA</option>
            <option value="83852">INACIO MARTINS</option>
            <option value="83864">INAJA</option>
            <option value="83876">INDIANOPOLIS</option>
            <option value="83924">IPIRANGA</option>
            <option value="83936">IPORA</option>
            <option value="83948">IRACEMA DO OESTE</option>
            <option value="83972">IRATI</option>
            <option value="83996">IRETAMA</option>
            <option value="84032">ITAGUAJE</option>
            <option value="80476">ITAIPULANDIA</option>
            <option value="84056">ITAMBARACA</option>
            <option value="84068">ITAMBE</option>
            <option value="84092">ITAPEJARA DO OESTE</option>
            <option value="84098">ITAPERUCU</option>
            <option value="84116">ITAUNA DO SUL</option>
            <option value="84128">IVAI</option>
            <option value="84164">IVAIPORA</option>
            <option value="84188">IVATE</option>
            <option value="84200">IVATUBA</option>
            <option value="84224">JABOTI</option>
            <option value="84236">JACAREZINHO</option>
            <option value="84296">JAGUAPITA</option>
            <option value="84308">JAGUARIAIVA</option>
            <option value="84332">JANDAIA DO SUL</option>
            <option value="84380">JANIOPOLIS</option>
            <option value="84392">JAPIRA</option>
            <option value="84404">JAPURA</option>
            <option value="84428">JARDIM ALEGRE</option>
            <option value="84440">JARDIM OLINDA</option>
            <option value="84464">JATAIZINHO</option>
            <option value="84476">JESUITAS</option>
            <option value="84500">JOAQUIM TAVORA</option>
            <option value="84548">JUNDIAI DO SUL</option>
            <option value="84560">JURANDA</option>
            <option value="84572">JUSSARA</option>
            <option value="84596">KALORE</option>
            <option value="84644">LAPA</option>
            <option value="84656">LARANJAL</option>
            <option value="84668">LARANJEIRAS DO SUL</option>
            <option value="84704">LEOPOLIS</option>
            <option value="84728">LIDIANOPOLIS</option>
            <option value="84732">LINDOESTE</option>
            <option value="84764">LOANDA</option>
            <option value="84776">LOBATO</option>
            <option value="84800">LONDRINA</option>
            <option value="84824">LUIZIANA</option>
            <option value="84836">LUNARDELLI</option>
            <option value="84848">LUPIONOPOLIS</option>
            <option value="84884">MALLET</option>
            <option value="84908">MAMBORE</option>
            <option value="84920">MANDAGUACU</option>
            <option value="84932">MANDAGUARI</option>
            <option value="84956">MANDIRITUBA</option>
            <option value="82776">MANFRINOPOLIS</option>
            <option value="84968">MANGUEIRINHA</option>
            <option value="84980">MANOEL RIBAS</option>
            <option value="85028">MARECHAL CANDIDO RONDON</option>
            <option value="85052">MARIA HELENA</option>
            <option value="85064">MARIALVA</option>
            <option value="85088">MARILANDIA DO SUL</option>
            <option value="85100">MARILENA</option>
            <option value="85124">MARILUZ</option>
            <option value="85148">MARINGA</option>
            <option value="85160">MARIOPOLIS</option>
            <option value="89768">MARIPA</option>
            <option value="85196">MARMELEIRO</option>
            <option value="85220">MARQUINHO</option>
            <option value="85232">MARUMBI</option>
            <option value="85244">MATELANDIA</option>
            <option value="85256">MATINHOS</option>
            <option value="85265">MATO RICO</option>
            <option value="85268">MAUA DA SERRA</option>
            <option value="85280">MEDIANEIRA</option>
            <option value="85294">MERCEDES</option>
            <option value="85304">MIRADOR</option>
            <option value="85328">MIRASELVA</option>
            <option value="85352">MISSAL</option>
            <option value="85388">MOREIRA SALES</option>
            <option value="85400">MORRETES</option>
            <option value="85424">MUNHOZ DE MELO</option>
            <option value="85532">NOSSA SENHORA DAS GRACAS</option>
            <option value="85544">NOVA ALIANCA DO IVAI</option>
            <option value="85556">NOVA AMERICA DA COLINA</option>
            <option value="85580">NOVA AURORA</option>
            <option value="85652">NOVA CANTU</option>
            <option value="85676">NOVA ESPERANCA</option>
            <option value="85664">NOVA ESPERANCA DO SUDOESTE</option>
            <option value="85700">NOVA FATIMA</option>
            <option value="89828">NOVA LARANJEIRAS</option>
            <option value="85736">NOVA LONDRINA</option>
            <option value="85772">NOVA OLIMPIA</option>
            <option value="85784">NOVA PRATA DO IGUACU</option>
            <option value="87596">NOVA SANTA BARBARA</option>
            <option value="85820">NOVA SANTA ROSA</option>
            <option value="85826">NOVA TEBAS</option>
            <option value="84008">NOVO ITACOLOMI</option>
            <option value="85928">ORTIGUEIRA</option>
            <option value="85952">OURIZONA</option>
            <option value="85964">OURO VERDE DO OESTE</option>
            <option value="86012">PAICANDU</option>
            <option value="86024">PALMAS</option>
            <option value="86036">PALMEIRA</option>
            <option value="86072">PALMITAL</option>
            <option value="86108">PALOTINA</option>
            <option value="86156">PARAISO DO NORTE</option>
            <option value="86168">PARANACITY</option>
            <option value="86204">PARANAGUA</option>
            <option value="86228">PARANAPOEMA</option>
            <option value="86240">PARANAVAI</option>
            <option value="86276">PATO BRAGADO</option>
            <option value="86288">PATO BRANCO</option>
            <option value="86336">PAULA FREITAS</option>
            <option value="86360">PAULO FRONTIN</option>
            <option value="86384">PEABIRU</option>
            <option value="86420">PEROBAL</option>
            <option value="86432">PEROLA</option>
            <option value="86444">PEROLA DO OESTE</option>
            <option value="86468">PIEN</option>
            <option value="86492">PINHAIS</option>
            <option value="86516">PINHAL DE SAO BENTO</option>
            <option value="86504">PINHALAO</option>
            <option value="86552">PINHAO</option>
            <option value="86588">PIRAI DO SUL</option>
            <option value="86612">PIRAQUARA</option>
            <option value="86636">PITANGA</option>
            <option value="86648">PITANGUEIRAS</option>
            <option value="86660">PLANALTINA DO PARANA</option>
            <option value="86673">PLANALTO</option>
            <option value="86696">PONTA GROSSA</option>
            <option value="86888">PONTAL DO PARANA</option>
            <option value="86720">PORECATU</option>
            <option value="86744">PORTO AMAZONAS</option>
            <option value="86827">PORTO BARREIRO</option>
            <option value="86816">PORTO RICO</option>
            <option value="86864">PORTO VITORIA</option>
            <option value="89872">PRADO FERREIRA</option>
            <option value="86900">PRANCHITA</option>
            <option value="86924">PRESIDENTE CASTELO BRANCO</option>
            <option value="86948">PRIMEIRO DE MAIO</option>
            <option value="86972">PRUDENTOPOLIS</option>
            <option value="87008">QUARTO CENTENARIO</option>
            <option value="86996">QUATIGUA</option>
            <option value="87020">QUATRO BARRAS</option>
            <option value="87044">QUATRO PONTES</option>
            <option value="87056">QUEDAS DO IGUACU</option>
            <option value="87068">QUERENCIA DO NORTE</option>
            <option value="87080">QUINTA DO SOL</option>
            <option value="87092">QUITANDINHA</option>
            <option value="87104">RAMILANDIA</option>
            <option value="87112">RANCHO ALEGRE</option>
            <option value="87116">RANCHO ALEGRE D'OESTE</option>
            <option value="87128">REALEZA</option>
            <option value="87140">REBOUCAS</option>
            <option value="87164">RENASCENCA</option>
            <option value="87188">RESERVA</option>
            <option value="87454">RESERVA DO IGUACU</option>
            <option value="87200">RIBEIRAO CLARO</option>
            <option value="87212">RIBEIRAO DO PINHAL</option>
            <option value="87224">RIO AZUL</option>
            <option value="87236">RIO BOM</option>
            <option value="87248">RIO BONITO DO IGUACU</option>
            <option value="87271">RIO BRANCO DO IVAI</option>
            <option value="87272">RIO BRANCO DO SUL</option>
            <option value="87344">RIO NEGRO</option>
            <option value="87428">ROLANDIA</option>
            <option value="87440">RONCADOR</option>
            <option value="87464">RONDON</option>
            <option value="87470">ROSARIO DO IVAI</option>
            <option value="87476">SABAUDIA</option>
            <option value="87500">SALGADO FILHO</option>
            <option value="87524">SALTO DO ITARARE</option>
            <option value="87536">SALTO DO LONTRA</option>
            <option value="87560">SANTA AMELIA</option>
            <option value="87608">SANTA CECILIA DO PAVAO</option>
            <option value="87644">SANTA CRUZ DE MONTE CASTELO</option>
            <option value="87680">SANTA FE</option>
            <option value="87692">SANTA HELENA</option>
            <option value="87704">SANTA INES</option>
            <option value="87716">SANTA ISABEL DO IVAI</option>
            <option value="87728">SANTA IZABEL DO OESTE</option>
            <option value="87740">SANTA LUCIA</option>
            <option value="87782">SANTA MARIA DO OESTE</option>
            <option value="87800">SANTA MARIANA</option>
            <option value="87812">SANTA MONICA</option>
            <option value="87848">SANTA TEREZA DO OESTE</option>
            <option value="87860">SANTA TEREZINHA DE ITAIPU</option>
            <option value="87584">SANTANA DO ITARARE</option>
            <option value="87944">SANTO ANTONIO DA PLATINA</option>
            <option value="87896">SANTO ANTONIO DO CAIUA</option>
            <option value="87932">SANTO ANTONIO DO PARAISO</option>
            <option value="87956">SANTO ANTONIO DO SUDOESTE</option>
            <option value="87968">SANTO INACIO</option>
            <option value="88016">SAO CARLOS DO IVAI</option>
            <option value="88124">SAO JERONIMO DA SERRA</option>
            <option value="88136">SAO JOAO</option>
            <option value="88160">SAO JOAO DO CAIUA</option>
            <option value="88172">SAO JOAO DO IVAI</option>
            <option value="88196">SAO JOAO DO TRIUNFO</option>
            <option value="88232">SAO JORGE DO IVAI</option>
            <option value="88244">SAO JORGE DO OESTE</option>
            <option value="88221">SAO JORGE DO PATROCINIO</option>
            <option value="88280">SAO JOSE DA BOA VISTA</option>
            <option value="88274">SAO JOSE DAS PALMEIRAS</option>
            <option value="88316">SAO JOSE DOS PINHAIS</option>
            <option value="88412">SAO MANOEL DO PARANA</option>
            <option value="88436">SAO MATEUS DO SUL</option>
            <option value="88472">SAO MIGUEL DO IGUACU</option>
            <option value="88478">SAO PEDRO DO IGUACU</option>
            <option value="88508">SAO PEDRO DO IVAI</option>
            <option value="88520">SAO PEDRO DO PARANA</option>
            <option value="88604">SAO SEBASTIAO DA AMOREIRA</option>
            <option value="88652">SAO TOME</option>
            <option value="88712">SAPOPEMA</option>
            <option value="88724">SARANDI</option>
            <option value="88736">SAUDADE DO IGUACU</option>
            <option value="88784">SENGES</option>
            <option value="88825">SERRANOPOLIS DO IGUACU</option>
            <option value="88844">SERTANEJA</option>
            <option value="88856">SERTANOPOLIS</option>
            <option value="88916">SIQUEIRA CAMPOS</option>
            <option value="88760">SULINA</option>
            <option value="88988">TAMARANA</option>
            <option value="89000">TAMBOARA</option>
            <option value="89012">TAPEJARA</option>
            <option value="89024">TAPIRA</option>
            <option value="89048">TEIXEIRA SOARES</option>
            <option value="89060">TELEMACO BORBA</option>
            <option value="89096">TERRA BOA</option>
            <option value="89120">TERRA RICA</option>
            <option value="89132">TERRA ROXA</option>
            <option value="89144">TIBAGI</option>
            <option value="89156">TIJUCAS DO SUL</option>
            <option value="89180">TOLEDO</option>
            <option value="89192">TOMAZINA</option>
            <option value="89204">TRES BARRAS DO PARANA</option>
            <option value="89288">TUNAS DO PARANA</option>
            <option value="89300">TUNEIRAS DO OESTE</option>
            <option value="89312">TUPASSI</option>
            <option value="89336">TURVO</option>
            <option value="89384">UBIRATA</option>
            <option value="89408">UMUARAMA</option>
            <option value="89432">UNIAO DA VITORIA</option>
            <option value="89444">UNIFLOR</option>
            <option value="89456">URAI</option>
            <option value="89540">VENTANIA</option>
            <option value="89564">VERA CRUZ DO OESTE</option>
            <option value="89588">VERE</option>
            <option value="89942">VIRMOND</option>
            <option value="89978">VITORINO</option>
            <option value="89528">WENCESLAU BRAZ</option>
            <option value="89986">XAMBRE</option>
            <option value="99000">OUTROS ESTADOS</option>
        </select>
    </div>
</template>

<script>
    export default {
        props: ['id_municipio']
    }
</script>

<style scoped>

</style>